name: Test Timeout

on: [push]

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: start job
        run: echo "This job will timeout if it runs longer than 5 minutes"

      - name: Run Long Process
        run: |
          echo "Starting..."
          sleep 400
          echo "Completed"
